### PR TITLE
Incorporate a more user-friendly argsParser

### PR DESCRIPTION
**Pull request by alfredomusumeci**
Effectively the same as https://github.com/goldmansachs/crdtools/pull/53. Renaming the branch to a better name for this PR has caused the other one to close.

### CODE REVIEW

**Comment by alfredomusumeci** [comment]
Fixing the missing EOL and updating...

**Comment by alfredomusumeci** [comment]
All updated!

**Comment by nresare** [comment]
Having experimented using this a little bit there are some usability aspects that I think it makes sense to change, just to increase usability somewhat. Unix command line tools has options and positional arguments. Options start with dash or double dash, and can either be without arguments or have one argument (or, in some cases a comma separated list of arguments). Positional arguments on the other hand can be many. I think it would make sense to have the input CRDs be positional arguments and not an option with an arbitrary number of arguments.

**Comment by alfredomusumeci** [comment]
> Having experimented using this a little bit there are some usability aspects that I think it makes sense to change, just to increase usability somewhat. Unix command line tools has options and positional arguments. Options start with dash or double dash, and can either be without arguments or have one argument (or, in some cases a comma separated list of arguments). Positional arguments on the other hand can be many. I think it would make sense to have the input CRDs be positional arguments and not an option with an arbitrary number of arguments.

I am currently trying to land a V1 of the Yamlifier with minimal use-case (https://github.com/goldmansachs/crdtools/issues/9) between today and tomorrow and will work on this next!

**Comment by alfredomusumeci** [comment]
Updated with changes ad discussed

**Review by nresare — APPROVED** [review]
lgtm

**Pull request merged**
