### PR TITLE
Temporary OpenAPIGen folder is now deleted

### PR DESCRIPTION
**Pull request by alfredomusumeci**
Created a helper class (Utils) to help with the deletion of the folder OpenAPIGen and its content.

### CODE REVIEW

**Review by nresare — CHANGES_REQUESTED** [review]
Let's make this a method in SourceGenFromSpec instead.

**Comment by alfredomusumeci** [comment]
Done

**Comment by alfredomusumeci** [comment]
I think this can now be closed as there is another implementation of delete folder in the SourceGen

**Comment by nresare** [comment]
Ok, this is a bit embarrassing. Did I forget about this one?

**Comment by nresare** [comment]
Ok, cheers! Closing

**Pull request closed without merging**
